### ISSUE TITLE
Can I use this with non-WASM projects?

### ISSUE THREAD

**Issue by rohsaurus** [nemequ/wasmv#4]
Sorry to bother you. I'm trying to learn SIMD, and I like the focus on safety of this project. Is it possible to use this with a project that compiles to an application, rather than web assembly. Sorry if this is an obvious question.

**Comment by nemequ** [comment]
It is possible. You can use the [`WAV_EMULATION`](https://github.com/nemequ/wav?tab=readme-ov-file#emulation) macro to make it possible to compile to other targets.

It's not an obvious question at all; many of the functions in WAV are implemented using portable code which relies on the compiler knowing how to optimize to the right instruction. However, there are some functions which I wasn't able to get the compiler to optimize to the desired instruction, by default it will call an architecture-specific intrinsic. For example, here is what `wav_f32x4_min` looks like (think of the `WAV_PORTABLE_SLOW(bugnum)` macro as `WAV_EMULATION`):

```c
WAV_FUNCTION_ATTRIBUTES
wav_f32x4_t
wav_f32x4_min(wav_f32x4_t a, wav_f32x4_t b)  {
  #if WAV_PORTABLE_SLOW(50805)
    return wav_f32x4_blend(
      wav_b32x4_or(
        wav_f32x4_ne(a, a),
        wav_f32x4_lt(a, b)
      ),
      a, b
    );
  #else
    return (wav_f32x4_t) { __builtin_wasm_min_f32x4(a.values, b.values) };
  #endif
}
```

The reason for the `WAV_PORTABLE_SLOW(bugnum)` macro is documentation; the numbers should correspond to a bug number on the [LLVM Bugzilla](https://bugs.llvm.org/index.cgi).

One thing that might dissuade you from doing this, though, is that WAV only works with clang-based compilers, primarily due to a reliance on the [`overloadable`](https://clang.llvm.org/docs/AttributeReference.html#overloadable).
